package com.model;


/**
 * TKefang generated by MyEclipse Persistence Tools
 */

public class TKefang implements java.io.Serializable
{

	private Integer id;
	private String fangjianhao;
	private String area;
	private String jieshao;

	private String fujian;
	private Integer qianshu;
	private Integer catelogId;
	private String del;
	
	private TCatelog catelog;

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public TCatelog getCatelog()
	{
		return catelog;
	}

	public void setCatelog(TCatelog catelog)
	{
		this.catelog = catelog;
	}

	public String getFangjianhao()
	{
		return this.fangjianhao;
	}

	public void setFangjianhao(String fangjianhao)
	{
		this.fangjianhao = fangjianhao;
	}

	public String getArea()
	{
		return this.area;
	}

	public void setArea(String area)
	{
		this.area = area;
	}

	public String getJieshao()
	{
		return this.jieshao;
	}

	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public Integer getQianshu()
	{
		return this.qianshu;
	}

	public void setQianshu(Integer qianshu)
	{
		this.qianshu = qianshu;
	}

	public Integer getCatelogId()
	{
		return this.catelogId;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}


	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}