package com.model;

/**
 * TPinglun generated by MyEclipse Persistence Tools
 */

public class TPinglun implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer kefangId;

	private String content;

	private String shijian;

	// Constructors

	/** default constructor */
	public TPinglun()
	{
	}

	/** full constructor */
	public TPinglun(Integer kefangId, String content, String shijian)
	{
		this.kefangId = kefangId;
		this.content = content;
		this.shijian = shijian;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getKefangId()
	{
		return this.kefangId;
	}

	public void setKefangId(Integer kefangId)
	{
		this.kefangId = kefangId;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

}