package com.model;

import java.util.Date;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{

	private Integer userId;
	private String userName;
	private String userPw;
	private String userRealname;//�ǳ�
	
	private String userAddress;
	private String userSex;
	private String userTel;
	private String userEmail;
	
	private String userQq;
	private String fujian;//ͷ��
	private String userType;//vip,putong
	private String userDel;
	
	
	
	public String getUserAddress()
	{
		return userAddress;
	}
	public void setUserAddress(String userAddress)
	{
		this.userAddress = userAddress;
	}
	public String getUserDel()
	{
		return userDel;
	}
	public void setUserDel(String userDel)
	{
		this.userDel = userDel;
	}
	public String getUserEmail()
	{
		return userEmail;
	}
	public void setUserEmail(String userEmail)
	{
		this.userEmail = userEmail;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public String getUserName()
	{
		return userName;
	}
	
	public String getUserType()
	{
		return userType;
	}
	public void setUserType(String userType)
	{
		this.userType = userType;
	}
	public void setUserName(String userName)
	{
		this.userName = userName;
	}
	public String getUserPw()
	{
		return userPw;
	}
	public void setUserPw(String userPw)
	{
		this.userPw = userPw;
	}
	public String getUserQq()
	{
		return userQq;
	}
	public void setUserQq(String userQq)
	{
		this.userQq = userQq;
	}
	public String getUserRealname()
	{
		return userRealname;
	}
	public void setUserRealname(String userRealname)
	{
		this.userRealname = userRealname;
	}
	public String getUserSex()
	{
		return userSex;
	}
	public void setUserSex(String userSex)
	{
		this.userSex = userSex;
	}
	public String getUserTel()
	{
		return userTel;
	}
	public void setUserTel(String userTel)
	{
		this.userTel = userTel;
	}
	@Override
	public String toString() {
		return "TUser [userId=" + userId + ", userName=" + userName + ", userPw=" + userPw + ", userRealname="
				+ userRealname + ", userAddress=" + userAddress + ", userSex=" + userSex + ", userTel=" + userTel
				+ ", userEmail=" + userEmail + ", userQq=" + userQq + ", fujian=" + fujian + ", userType=" + userType
				+ ", userDel=" + userDel + "]";
	}
	
	
	
}